### ISSUE TITLE
Missing stepped easing mode

### ISSUE THREAD

**Issue by ArnCarveris** [mobius3/tweeny#11]
There is some use-case where I need stepped interpolation like in  [Spine](http://esotericsoftware.com/spine-graph#Stepped)

The current workaround is to implement easing mode:
```cpp
namespace tweeny
{
    class easing_ex {
    public:
        static constexpr struct steppedEasing {
            template<typename T>
            static T run(float position, T start, T end) {
                return start;
            }
        } stepped = steppedEasing{};
    };
}
````
Implement type wrapper to avoid compile error due [this](https://github.com/mobius3/tweeny/blob/master/include/tweenpoint.tcc#L72) :
```cpp
namespace tweeny
{
    template<typename T>
    struct steppedWrapper : T
    {
        steppedWrapper() = default;
        steppedWrapper(steppedWrapper&&) = default;
        steppedWrapper(const steppedWrapper&) = default;

        template<typename... Args>
        explicit steppedWrapper(Args&&... args) :
            T{ std::forward<Args>(args)... }
        { }

        steppedWrapper& operator = (const steppedWrapper&) = default;
        steppedWrapper& operator = (const T& rhs)
        {
            T::operator = (rhs);
            
            return *this;
        }

        friend steppedWrapper operator - (const steppedWrapper& lhs, const steppedWrapper& rhs)
        {
            return lhs;
        }
        friend steppedWrapper operator + (const steppedWrapper& lhs, const steppedWrapper& rhs)
        {
            return lhs;
        }
        friend steppedWrapper operator * (const steppedWrapper& lhs, const steppedWrapper& rhs)
        {
            return lhs;
        }
        friend steppedWrapper operator * (const steppedWrapper& lhs, const float& rhs)
        {
            return lhs;
        }
        friend steppedWrapper operator * (const float& lhs, const steppedWrapper& rhs)
        {
            return rhs;
        }
    };
}
```
Test class:
```cpp
struct CSmth
{
    int frame{-1};
    void* user_data{nullptr};
};
```

Current code:
```cpp
    using smth_t = tweeny::steppedWrapper<CSmth>;

    auto t = tweeny::from(smth_t{7 })
        .to(smth_t{9}).during(300.0f)
        .via(tweeny::easing_ex::steppedEasing::run<smth_t>);

    t.step(0.1f);
```
Wanted code:
```cpp
    auto t = tweeny::from(CSmth{7 })
        .to(CSmth{9}).during(300.0f)
        .via(tweeny::easing::stepped);
    t.step(0.1f);
```

**Comment by mobius3** [comment]
I can totally see the use case for this. To be sure, your issue is about the missing stepped easing or about the need to create a wrapper class?

**Comment by ArnCarveris** [comment]
The wrapper is just a user-side hack to avoid a compilation error. So yes I need proper stepped easing support. Also, there should be default easing for an arithmetic type is must stay linear, but for the non-arithmetic type is must be only stepped, this will solve compilation error and avoids the need to implement useless wrapper.

**Comment by mobius3** [comment]
Noted. I'll work on it once I have time, thanks for the issue!

**Comment by ArnCarveris** [comment]
Approximately how much time it will take and when I should expect results? This month or next year?

**Comment by mobius3** [comment]
I'm not sure as this project doesn't pay my bills, but if this is urgent to you and you know how to do it, I'm keen on accepting a pull request once you have time to implement it yourself.

**Comment by ArnCarveris** [comment]
Done, there PR(https://github.com/mobius3/tweeny/pull/12) for stepped easing mode, and PR(https://github.com/mobius3/tweeny/pull/13) for non-arithmetic type aka default easing mode.

**Comment by mobius3** [comment]
Looks good. I've merged them but in the wrong order, I may have messed up the merge, can you check to see if it is ok before we close this issue?

**Comment by ArnCarveris** [comment]
It should be in the following order:
1. Default
2. Stepped

**Comment by mobius3** [comment]
I know but I committed them already. It seems to me they are ok (even in the wrong order), so If you can check if the result is as you intended to be (I had to rename your `default` easing mode because it was giving compilation errors on g++).

If the code looks ok to you, I will be closing this issue.
