### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by ArnCarveris** [mobius3/tweeny#14]
Code
```cpp
    struct A {};
    struct B {};

    auto t = tweeny::from(
        A{}, A{}, B{}
    ).to(
        A{}, A{}, B{}
    ).during(1000.0f);
```
Error [C2078](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2078?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(C2078)%26rd%3Dtrue&view=vs-2019) at: https://github.com/ArnCarveris/tweeny/blob/wip/include/tweenpoint.tcc#L70

**Comment by mobius3** [comment]
I can reproduce your issue and I believe commit c5a3a86 has fixed it. Can you confirm?
