### ISSUE TITLE
Current Direction is ignored on 2 of 3 step functions

### ISSUE THREAD

**Issue by ghost** [mobius3/tweeny#19]
tweent.tcc

Only the first function:
inline const typename detail::tweentraits<T, Ts...>::valuesType & tween<T, Ts...>::step(int32_t dt, bool suppress) {
        return step(static_cast<float>(dt * currentDirection)/static_cast<float>(total), suppress);
    }

uses currentDirection. The other 2 step functions not

**Comment by mobius3** [comment]
Good find. It is supposed to be in just one of them but it was on the wrong one. Steepping is chained and they all resolve in the float version of it (`step(float, bool)`).
