### ISSUE TITLE
Cannot use project's CMakeLists. Link error if project included in workspace.

### ISSUE THREAD

**Issue by PicosePablo** [mobius3/tweeny#2]
Hi, i was trying to use your library, but the inconvenience is:
1-I cannot use Cmake with this CmakeList.
2-Link error if i try to use it including in my workspace. That .tcc extension does not work (i tried to change it to .h)

**Comment by mobius3** [comment]
Hi! Can you please describe what is your operating system, build tools (compiler version, cmake version, etc)  and how are you including the library in your project?

Why you say you cannot use this CMakeLists?

Additionally can you provide the whole build log so that I can help you better?

.tcc files should not be a problem.

Thank you for your report.

**Comment by jizc** [comment]
Hi @mobius3, I believe I'm having the same problem. I'm certain it's just a noob error on my part as I'm new to C++ (used to C#).

I'm using Visual Studio 2017 RC and I have:
- copied the include folder into my project (I'm not familiar with CMake yet)
- added the relative path to the include folder in my project settings (C/C++ -> General -> Additional Include Directories)
- added `#include "tweeny.h"` to my `stdafx.h` file

IntelliSense is functioning and I'm getting no errors pre-build. However, whenever I try to use `tweeny::from` and build the project, I get this error: `error LNK2001: unresolved external symbol "public: static struct tweeny::easing::<unnamed-type-linear> tweeny::easing::linear" (?linear@easing@tweeny@@2U<unnamed-type-linear>@12@A)`. If I only comment out the `tweeny::from` line, it builds again.

Any tips you can give would be very welcome! I've been Googling for hours now.

**Comment by mobius3** [comment]
I see. I've successfuly reproduced your problem, It is certainly a bug, not sure if in VC++ or tweeny itself, but its related to VC++ wanting a definition for a function when it shouldn't (or shouldn't need).

I'll try and fix it and get back to you.

Thanks for your information, it certainly helped.

**Comment by jizc** [comment]
Fantastic! Thank you so much for your fast reply 🥇

**Comment by mobius3** [comment]
I've made changes that should fix this. I tested on my machine with VS2015 CE. Can you confirm its fixed, please? Thanks!

**Comment by jizc** [comment]
Thank you for the update! I've tested it and it now compiles and appears to work 👍 

However, I'm getting a few warnings from my test (`auto test = tweeny::from(0).to(100000).during(5000);`).
If you're interested, here they are:
```
1>f:\game\libraries\tweeny\include\tweenone.tcc(117): warning C4244: 'initializing': conversion from 'float' to 'uint32_t', possible loss of data
1>f:\game\libraries\tweeny\include\tweenone.tcc(115): note: while compiling class template member function 'void tweeny::tween<int>::interpolate(float)'
1>f:\game\libraries\tweeny\include\tweenone.tcc(129): note: see reference to function template instantiation 'void tweeny::tween<int>::interpolate(float)' being compiled
1>f:\game\libraries\tweeny\include\tweenone.tcc(125): note: while compiling class template member function 'void tweeny::tween<int>::render(float)'
1>f:\game\libraries\tweeny\include\tweenone.tcc(94): note: see reference to function template instantiation 'void tweeny::tween<int>::render(float)' being compiled
1>f:\game\libraries\tweeny\include\tweenone.tcc(91): note: while compiling class template member function 'const int &tweeny::tween<int>::seek(float,bool)'
1>f:\game\libraries\tweeny\include\tweenone.tcc(85): note: see reference to function template instantiation 'const int &tweeny::tween<int>::seek(float,bool)' being compiled
1>f:\game\libraries\tweeny\include\tweenone.tcc(38): note: while compiling class template member function 'tweeny::tween<int>::tween(T)'
1>        with
1>        [
1>            T=int
1>        ]
1>f:\game\libraries\tweeny\include\tweenone.tcc(36): note: see reference to function template instantiation 'tweeny::tween<int>::tween(T)' being compiled
1>        with
1>        [
1>            T=int
1>        ]
1>f:\game\libraries\tweeny\include\tweenone.tcc(36): note: while compiling class template member function 'tweeny::tween<int> tweeny::tween<int>::from(T)'
1>        with
1>        [
1>            T=int
1>        ]
1>f:\game\libraries\tweeny\include\tweeny.tcc(36): note: see reference to function template instantiation 'tweeny::tween<int> tweeny::tween<int>::from(T)' being compiled
1>        with
1>        [
1>            T=int
1>        ]
1>f:\game\libraries\tweeny\include\tweenone.tcc(42): note: while compiling class template member function 'tweeny::tween<int> &tweeny::tween<int>::to(T)'
1>        with
1>        [
1>            T=int
1>        ]
1>f:\game\source\game.cpp(47): note: see reference to function template instantiation 'tweeny::tween<int> &tweeny::tween<int>::to(T)' being compiled
1>        with
1>        [
1>            T=int
1>        ]
1>f:\game\source\game.cpp(47): note: see reference to class template instantiation 'tweeny::tween<int>' being compiled

**Comment by mobius3** [comment]
I got those warnings too. They are harmless, as it seems, but I'll try to fix them. Thank you!

**Comment by jizc** [comment]
There were no other warnings than the ones I posted. I've now implemented it to move my camera with `tweeny::from(position.x, position.y).to(target.x, target.y).via(tweeny::easing::quarticOut).during(2000)` and that produces no errors (x and y are floats). So I assume the previous warnings are due to the int cast.

**Comment by mobius3** [comment]
Yeah, I forgot to add some casts in there. Will fix it soon.
