### ISSUE TITLE
Help with duration

### ISSUE THREAD

**Issue by flamendless** [mobius3/tweeny#23]
Hi, I have the following code:
```cpp
#define DUR_FADE_IN 1
#define DUR_FADE_OUT 50

tweeny::tween<float> t_sidebar;
tweeny::tween<float> t_si;

bool show_sidebar = false;

void SidebarHandler::init(Sidebar* sidebar, SidebarIndicator* sidebar_indicator)
{
	m_sidebar = sidebar;
	m_sidebar_indicator = sidebar_indicator;

	t_sidebar = tweeny::from(m_sidebar->m_alpha).to(1.0f); //starts at 0.0f
	t_si = tweeny::from(m_sidebar_indicator->m_alpha).to(0.0f); //starts at 1.0f
}

void SidebarHandler::update(float dt)
{
	const ImVec2& m_pos = ImGui::GetMousePos();
	const int min = Sidebar_c::pos.x + Sidebar_c::indicator_size.x;
	const int dist = m_pos.x - min;

	if (dist <= 0 || m_sidebar->m_has_opened)
		show_sidebar = true;
	else
		show_sidebar = false;

	if (show_sidebar)
	{
		t_sidebar.during(DUR_FADE_IN);
		t_si.during(DUR_FADE_IN);

		t_sidebar.forward();
		t_si.forward();
	}
	else
	{
		t_sidebar.during(DUR_FADE_OUT);
		t_si.during(DUR_FADE_OUT);

		t_sidebar.backward();
		t_si.backward();
	}

	const float da = t_sidebar.step(dt);
	const float da2 = t_si.step(dt);

	m_sidebar->m_alpha = da;
	m_sidebar_indicator->m_alpha = da2;
}
```
What the code does is that when the mouse is hovered in the side, the `sidebar indicator` (instant) should disappear while it shows the `sidebar` (instant). If unhovered, hide `sidebar` (should fade out) and show `sidebar indicator` (should fade in)

But what's happening is when i test the values:
* Making the `DUR_FADE_IN` to `1` makes it wait for delay before actually showing for some reason.
* Making the `DUR_FADE_IN` to `5` makes it wait for delay (same time as above) but with fading effect.

in other issues (and in the manual) ive observed that the values put in `during` is higher (around 1000), but in my it takes too long. maybe problem with `dt`? printing `dt` seems normal as i get around `0.0166667` and `0.00921989`

**Comment by mobius3** [comment]
Duration values are intentionally used as integer values inside tweeny and usually 1 duration unit is used as 1 millisecond so the easiest way to make it work in your case is to have your `dt` multiplied by `1000` and have your `DUR_` constants also multiplied by `1000` (assuming you wanted DUR_FADE_IN to have a 1s duration).

**Comment by mobius3** [comment]
```cpp
const ImVec2& m_pos = ImGui::GetMousePos();
const int min = Sidebar_c::pos.x + Sidebar_c::indicator_size.x;
const int dist = m_pos.x - min;

if (dist <= 0 || m_sidebar->m_has_opened)
show_sidebar = true;
else
show_sidebar = false;

if (show_sidebar)
{
t_sidebar.during(DUR_FADE_IN * 1000);
t_si.during(DUR_FADE_IN * 1000);

t_sidebar.forward();
t_si.forward();
}
else
{
t_sidebar.during(DUR_FADE_OUT * 1000);
t_si.during(DUR_FADE_OUT * 1000);

t_sidebar.backward();
t_si.backward();
}

const float da = t_sidebar.step(dt * 1000);
const float da2 = t_si.step(dt * 1000);

m_sidebar->m_alpha = da;
m_sidebar_indicator->m_alpha = da2;
```

So this is what I would do in your case.

**Comment by flamendless** [comment]
Thanks for the clarification!

I've changed the following:
```cpp
#define DUR_FADE_IN 1000
#define DUR_FADE_OUT 50000
//update
dt *= 1000;
```
the hover to appear instantly works, but the hovering out makes it disappear instantly as well (my aim is to make it fade out)

**Comment by mobius3** [comment]
I'll try to reproduce something based on your code, you might've found a bug. Your code is supposed to work. One potential problem that I see is maybe calling `duration()` every frame.

**Comment by flamendless** [comment]
Hmm but that shouldnt be a problem right? It's just setting the duration with the same value each frame 🤔

The reason I've moved setting of duration in update is so that i could avoid making two tweeny objects (fade in and fade out) for each (sidebar and sidebar indicator)

Thanks for taking the time helping me :)

**Comment by mobius3** [comment]
Hey, problem is that `tween::step(float)` does a different thing from `tween::step(int)`: the first interpolates a tween using steps in the percent domain (0-100%, where `0.0f` is 0% and `1.0f` is 100%), the second interpolates in the duration domain, in your case, for `DUR_FADE_IN`, that would be from 0 to 1000.

Try `t_sidebar.step((int) dt);` and `t_si.step((int) dt);`, see if it helps.

**Comment by flamendless** [comment]
The tweening for fade-in works (when mouse is hovered, but it should fade-in faster), but hovering out did not make it disappear or fade-out (tween should work here)

**Comment by mobius3** [comment]
It should. I'll keep investigating, but as a workaround you can create a new tween whenever the hove state changes. You can replace the original tween. Not sure if whatever you're using can track the hover state per frame, but if you are able to, I'd recommend something like this:


```cpp
void update(float dt) {
  if (hover_enter) {
    t_sidebar = tweeny::from(m_sidebar->alpha).to(1.0f).during(DUR_FADE_IN);
  } else if (hover_leave) {
    t_sidebar = tweeny::from(m_sidebar->alpha).to(0.0f).during(DUR_FADE_OUT);
  }
  m_sidebar->alpha = t_sidebar.step(static_cast<int>(dt * 1000));
}
```

**Comment by flamendless** [comment]
> Not sure if whatever you're using can track the hover state per frame

I'm using dearimgui and I can track the hover state per frame as shown by the usage of `show_sidebar` in the code below.

Hmm it's still misbehaving. Here's the updated code:
```cpp
//init
#define DUR_FADE_IN 1000
#define DUR_FADE_OUT 50000

//update
	const ImVec2& mouse_pos = ImGui::GetMousePos();
	const int min = Config::Sidebar_c::pos.x + Config::Sidebar_c::indicator_size.x;
	const int dist = mouse_pos.x - min;

	if ((dist <= 0 || m_sidebar->m_has_opened) && !CommandPalette::is_open)
		show_sidebar = true;
	else
		show_sidebar = false;

	if (show_sidebar)
	{
		t_sidebar = tweeny::from(m_sidebar->m_alpha).to(1.0f).during(DUR_FADE_IN);
		PLOGD << "1";
	}
	else
	{
		t_sidebar = tweeny::from(m_sidebar->m_alpha).to(0.0f).during(DUR_FADE_OUT);
		PLOGD << "2";
	}

	m_sidebar->m_alpha = t_sidebar.step(static_cast<int>(dt * 1000));
```

When i hover, it fades in and continuously prints `1`. But when I hover out, ~~it does not fade out~~, but the `2` gets printed continuously. 

EDIT:
after printing the value of the `step`, it does fade out but very very slowly. It seems that the value for the `DUR_FADE_IN` and `DUR_FADE_OUT` is too large.

Setting them to `100` and `500` matches the behavior im looking for. Thanks!

Quick question, isnt doing the `tweeny::from` each frame expensive? Is it creating a new tweeny object per frame??

**Comment by mobius3** [comment]
> Quick question, isnt doing the tweeny::from each frame expensive? Is it creating a new tweeny object per frame??

It is expensive indeed, that's why I said you should track when the sidebar has actually changed it's state so you only create a new tween in the same frame where the state has changed, it's also why I chose different variable names (`hover_enter` and `hover_leave`). From the looks of your actual code you might have to use 2 variables, one to track the previous state and another to track the current:

```cpp
// initial values
bool sidebar_visible = false, sidebar_was_visible = false;

sidebar_is_visible = (dist <= 0 || m_sidebar->m_has_opened) && !CommandPalette::is_open);
if (sidebar_is_visible && !sidebar_was_visible) { /* create fade in tween */ }
if (!sidebar_is_visible && sidebar_was_visible) { /* create fade out tween */ }
sidebar_was_visible = sidebar_is_visible;
```

**Comment by flamendless** [comment]
Got it. Thanks a lot!
