### ISSUE TITLE
How to make an std::vector of tweens?

### ISSUE THREAD

**Issue by ghost** [mobius3/tweeny#3]
I feel stupid for not figuring it out but everything I try gives me "template argument 1" errors...

**Comment by mobius3** [comment]
Hi!

You can only have a vector of the same type of tween, and you need to set explicitly the type of each value. For instance, for a tween of a single int:

```
std::vector<tweeny::tween<int>> tweenVec;
```

Can you post how you are trying to do it, so I can help you better?

**Comment by ghost** [comment]
Thanks for answering! Basically in my game loop I have an "update" function where I update the delta-time, and I want to put a loop that goes over all tweens in the vector (for convenience) and call tween.step(dt); on each one.

**Comment by mobius3** [comment]
Ah I see. Did you solved your problem then?

Em Dom, 12 de fev de 2017 13:07, Substance12 <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
Yep, it did. Thanks! And awesome library btw

**Comment by mobius3** [comment]
Glad it worked!

I'll close the issue, then.

**Comment by midn1** [comment]
I feel like I'm the stupid one, because I'm not sure how I'm supposed to design my game engine with this design choice. I thought of three approaches:

1. Single list of tagged union tweens (Clunky).
2. Separate lists of different tween types (Most simple on paper but could require many lists).
3. Single list of "tween bases". Edit the source to add runtime polymorphism (Most complicated).

All of them very "eh".

**Comment by mobius3** [comment]
This is a tough problem indeed. I'm assuming you know your types at compile time, so:

1) is very memory intensive and not type-safe unless you use RTTI
2) is what I'd do if I knew the types *at design time* (eg, I know my engine will have only support `tweeny<float>` or `tweeny<int, float>` types)
3) most complicated indeed, I'd say its not worth to edit tweeny sources to add runtime polymorphism.

There are more options, though, and it might combine your previous ones:

- If you don't know your types at design time but the user can provide them to you *at compile time*, there is some approaches described in [this](https://stackoverflow.com/questions/44021099/non-static-template-member-possible) stackoverflow question: 
  - The answer mapping types to indexes is really cool and might be viable in your case
  - My answer also might work well
  - In any case, this is your option 2) but with semi-automatic vector declaration
- There might be some heterogeneous containers around in those metaprogramming libraries
- If you don't know your types at compile time *at all* or can't expose templates to your user, you might be better off using just `tweeny<float, float, float, float>`, which should be enough for most cases (I've seen some code using tweeny like that)

In any case, it all boils down if you know your types or not (and this is true every time you might think you want an heterogeneous container) and when you'll know them. Sadly, all options are disappointing. I'm sorry :)

**Comment by midn1** [comment]
Darn, but I suppose that, yeah, `tweeny<float>` is enough for most things. Though if I have to interpolate matrices that'd get funky. Thanks for your input.
