### ISSUE TITLE
Any ideas how to use it without STL ?

### ISSUE THREAD

**Issue by makimy** [mobius3/tweeny#39]
Hi !

Probably the most popular question , yet i'm unable to find answer looking through the code.
There're lots of containers in use, is it possible to make them optional ?

**Comment by mobius3** [comment]
Hello! Sadly it's not possible to use tweeny without STL yet, not the way it is. I'd change stl containers to compatible ones. Ideally they should be a template argument for all the tweeny classes using STL containers. Or maybe they could be defined by pre-processor arguments.

Sadly I lack the time right now to make that change but I'm willing to accept pull requests :)

**Comment by makimy** [comment]
Oh, it is not that simple to implement everything, especially those "string" thingies that I didn't even try to play with.  Just made it from scratch, thanks for the "easing" functions.

**Comment by makimy** [comment]
They're beautiful
https://github.com/makimy/functions

You're genious !
