### ISSUE TITLE
Instructions on how to run the samples?

### ISSUE THREAD

**Issue by meniku** [mobius3/tweeny#4]
I cloned the repro and then ran 
`cmake .`

I get the following output:

> ➜  tweeny git:(master) cmake .
> -- The C compiler identification is AppleClang 8.1.0.8020038
> -- The CXX compiler identification is AppleClang 8.1.0.8020038
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at examples/CMakeLists.txt:58 (find_package):
>   By not providing "FindSDL2.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "SDL2", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "SDL2" with any of
>   the following names:
> 
>     SDL2Config.cmake
>     sdl2-config.cmake
> 
>   Add the installation prefix of "SDL2" to CMAKE_PREFIX_PATH or set
>   "SDL2_DIR" to a directory containing one of the above files.  If "SDL2"
>   provides a separate development package or SDK, be sure it has been
>   installed.
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/wakka/tmp/tweeny/CMakeFiles/CMakeOutput.log".

Are there some instructions somewhere?

**Comment by meniku** [comment]
ok I got around that by actually installing SDL2.

`cmake .` runs fine now. However I'm now stuck when running `make`:

> ➜  tweeny git:(master) ✗ make
> Scanning dependencies of target easings
> [  8%] Building CXX object examples/CMakeFiles/easings.dir/easings/easings.cpp.o
> [ 16%] Linking CXX executable easings
> ld: can't open output file for writing: easings, errno=21 for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [examples/easings] Error 1
> make[1]: *** [examples/CMakeFiles/easings.dir/all] Error 2
> make: *** [all] Error 2

**Comment by mobius3** [comment]
Hi! Thanks for your report.

I suspect this is happening because you are running cmake in the same directory of the project files.

Try creating a `build/` folder inside tweeny's path and then `cmake ..` inside. It should work.

**Comment by meniku** [comment]
thanks for the quick answer.

> ➜  tweeny git:(master) ✗ mkdir build
> ➜  tweeny git:(master) ✗ cd build
> ➜  build git:(master) ✗ cmake ..
> -- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/wakka/tmp/tweeny
> ➜  build git:(master) ✗ make
> make: *** No targets specified and no makefile found.  Stop.

did you ever test it on OS X?

**Comment by mobius3** [comment]
Oh. You will have to clone the repository again (or cleanup files that
weren't there), your last cmake execution left some files. Repeat the
process as above, it should work then.

Em Sex, 7 de abr de 2017 09:19, NiKu <notifications@github.com> escreveu:

**Comment by mobius3** [comment]
>>> did you ever test it on OS X?

The errors you are having aren't related or specific to the OS X platform yet. I'm sorry for the lack of instruction on how to run the examples, though. I'll improve the README.

Meanwhile, try this:
```
git clone https://github.com/mobius3/tweeny.git other-tweeny
mkdir other-tweeny/build
cd other-tweeny/build
cmake ../
make
```
Running this exact series of commands on  macOS Sierra builds all the examples properly.

**Comment by mobius3** [comment]
@meniku Did it worked?

**Comment by meniku** [comment]
Yep it worked, thanks.

**Comment by mobius3** [comment]
Ok. closing the issue then.
