### ISSUE TITLE
Weird behaviour with multi-valued, multi-point tweens. 

### ISSUE THREAD

**Issue by atilimcetin** [mobius3/tweeny#5]
Hi,

First, thank you for providing such a great library.

With multi-valued and multi-point tweens, I cannot get the correct results. For example, for this small piece of code:

```
auto tween = tweeny::from(0.5f, 1.f)
        .to(0.f, 1.f).during(10)
        .to(0.f, 0.f).during(10);

for (auto i = 0; i < 20; ++i)
{
    auto p = tween.step(1);
    std::cout << p[0] << " " << p[1] << "\n";
}
```

the output is:
```
0.475 1
0.45 1
0.425 1
0.4 1
0.375 1
0.35 1
0.325 1
0.3 1
0.275 1
0.25 1
0 0.45
0 0.4
0 0.35
0 0.3
0 0.25
0 0.2
0 0.15
0 0.0999998
0 0.0499998
0 0
```

But I think the output should be:
```
0.45 1
0.4 1
0.35 1
0.3 1
0.25 1
0.2 1
0.15 1
0.1 1
0.05 1
0 1
0 0.9
0 0.8
0 0.7
0 0.6
0 0.5
0 0.4
0 0.3
0 0.2
0 0.1
0 0
```

Maybe I'm missing a point but I cannot get the correct results.

Thanks

**Comment by mobius3** [comment]
I'll look into it, thanks for your report.

**Comment by mobius3** [comment]
You are correct. It only happens on multi-valued tweens indeed. It appears to be miscalculating progress on them. I'm still investigating, though. Thanks again :)

**Comment by mobius3** [comment]
I believe I have fixed the issue, I obtained the expected results. Can you test commit a08f6a5, please?

**Comment by atilimcetin** [comment]
Now it's working like a charm. Thanks for very quick fix :)
